[package]
name = "dicers"
version = "0.3.0"
authors = ["Tidle <tidle@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rand = "0.7.3"